### ISSUE TITLE
onChange() is only available in iOS 14.0 or newer

### ISSUE THREAD

**Issue by Skk-tj** [joekndy/MarqueeText#10]
It seems like Xcode is not happy with the `onChange()` in `MarqueeText.swift`. My deployment target is iOS 15.2. 

<img width="1511" alt="Screen Shot 2022-04-02 at 01 57 11" src="https://user-images.githubusercontent.com/11616436/161375735-6d26ecd8-c399-4ffe-8834-c45c21b32795.png">

**Comment by skyfoxa** [comment]
I opened a new PR #13 for this issue. It adds a backwards compatibility for iOS 13 so the package min iOS version doesn't have to be updated to iOS 14.
